name: opendata

services:
  labelbk:
    build:
      dockerfile: Dockerfile.label.local
    ports:
      - ${LABEL_API_PORT}:${LABEL_API_PORT}
    env_file:
      - .env
    volumes:
      - .:/home/node
    extra_hosts:
      - "host.docker.internal:host-gateway"

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.2
    command: [ "start-dev", "--import-realm" ]
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    volumes:
      - ./keycloak-realm-config.json:/opt/keycloak/data/import/keycloak-realm-config.json
    ports:
      - "8080:8080"

  labelDb:
    image: mongo:4.4
    command: mongod --port 55431
    volumes:
      - mongo-storage:/data/db
    expose:
      - 55431
    ports:
      - 55431:55431

volumes:
  mongo-storage:
    driver: local
    name: label-mongo-storage
