name: opendata

services:
  labelbk:
    build:
      dockerfile: Dockerfile.label.local
    ports:
      - ${LABEL_API_PORT}:${LABEL_API_PORT}
    env_file:
      - .env
    volumes:
      - .:/home/node
    extra_hosts:
      - "host.docker.internal:host-gateway"
    
