---
jobs:
  - name: "tobetreated-document-import"
    schedule: "*/15 6-17 * * *"
    successful_jobs_history_limit: 7
    failed_jobs_history_limit: 7
    backoff_limit: 0
    restartPolicy: "Never"
    parallelism: 1
    active_deadline_seconds: 1800
    command: "dist/courDeCassation/scripts/autoImportDocumentsFromSder.js"
  - name: "export-j-7"
    schedule: "25 18 * * *"
    successful_jobs_history_limit: 7
    failed_jobs_history_limit: 7
    backoff_limit: 2
    restartPolicy: "OnFailure"
    parallelism: 1
    active_deadline_seconds: 300
    command: "dist/courDeCassation/scripts/exportTreatedDocumentsSince.js --days 7"
  - name: "export-publishable"
    schedule: "50 13 * * *"
    successful_jobs_history_limit: 7
    failed_jobs_history_limit: 7
    backoff_limit: 2
    restartPolicy: "OnFailure"
    parallelism: 1
    active_deadline_seconds: 300
    command: "dist/courDeCassation/scripts/exportTreatedPublishableDocuments.js"
  - name: "free-pending"
    schedule: "*/16 6-17 * * *"
    successful_jobs_history_limit: 7
    failed_jobs_history_limit: 7
    backoff_limit: 0
    restartPolicy: "Never"
    parallelism: 1
    active_deadline_seconds: 300
    command: "dist/courDeCassation/scripts/freePendingDocuments.js"
  - name: "purge-m-12"
    schedule: "0 19 * * *"
    successful_jobs_history_limit: 7
    failed_jobs_history_limit: 7
    backoff_limit: 2
    restartPolicy: "Never"
    parallelism: 1
    active_deadline_seconds: 300
    command: "dist/courDeCassation/scripts/purgeDb.js --beforeMonths 12"
  - name: "renew-cache"
    schedule: "*/5 6-17 * * *"
    successful_jobs_history_limit: 3
    failed_jobs_history_limit: 7
    backoff_limit: 0
    restartPolicy: "Never"
    parallelism: 1
    active_deadline_seconds: 300
    command: "dist/courDeCassation/scripts/renewCache.js --beforeMinutes 5"
  - name: "cleaning"
    schedule: "30 19 * * *"
    successful_jobs_history_limit: 7
    failed_jobs_history_limit: 7
    backoff_limit: 3
    restartPolicy: "OnFailure"
    parallelism: 1
    active_deadline_seconds: 600
    command: "dist/courDeCassation/scripts/cleanDocuments.js"
